version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8120:8080"
    restart: always
    container_name: links-redirect
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_GENERATE_DDL: "true"
      SERVER_PORT: 8080
      DOMAIN_REDIRECT: ${DOMAIN_REDIRECT}
    deploy:
      resources:
        limits:
          memory: 100M